### ISSUE TITLE
Main doesnt run

### ISSUE THREAD

**Issue by Napolitain** [Jonitr0/WarnoModEditor#9]
Hi, i cannot run the main branch using

```
python -m pip install -r requirements.txt
python main.py
```

Any ideas?

```
D:\Repos\warno_balance\.venv\Scripts\python.exe D:\Repos\warno_balance\WarnoModEditor\main.py 
Traceback (most recent call last):
  File "D:\Repos\warno_balance\WarnoModEditor\main.py", line 8, in <module>
    from src import main_window
  File "D:\Repos\warno_balance\WarnoModEditor\src\main_window.py", line 4, in <module>
    from src.wme_widgets import base_window, main_widget
  File "D:\Repos\warno_balance\WarnoModEditor\src\wme_widgets\main_widget.py", line 8, in <module>
    from src.wme_widgets.tab_widget import wme_tab_widget, wme_detached_tab
  File "D:\Repos\warno_balance\WarnoModEditor\src\wme_widgets\tab_widget\wme_tab_widget.py", line 10, in <module>
    from src.wme_widgets.tab_pages.napo_pages import game_settings_page
  File "D:\Repos\warno_balance\WarnoModEditor\src\wme_widgets\tab_pages\napo_pages\game_settings_page.py", line 7, in <module>
    from src.wme_widgets.tab_pages.napo_pages import base_napo_page
  File "D:\Repos\warno_balance\WarnoModEditor\src\wme_widgets\tab_pages\napo_pages\base_napo_page.py", line 10, in <module>
    from src.ndf_parser.antlr_output.NdfGrammarLexer import NdfGrammarLexer
ModuleNotFoundError: No module named 'src.ndf_parser.antlr_output'
```

Thanks!

**Comment by Jonitr0** [comment]
You'd have to install ANTLR and create the parser code, but that is no longer necessary with v0.4.0
